apiVersion: v2
name: cassandra
description: Apache Cassandra wide column distributed database
type: application
version: 0.1.0
appVersion: "5.0"
home: https://github.com/kymeliodev/kymelio-helm
sources:
  - https://github.com/kymeliodev/kymelio-helm
keywords:
  - cassandra
  - database
  - nosql
  - wide-column
  - distributed
maintainers:
  - name: Kymelio
    email: simon.meier@kymelio.com
