apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitlab.fullname" . }}-headless
  labels:
    {{- include "gitlab.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.portName }}
      protocol: TCP
      name: {{ .Values.service.portName }}
    {{- if .Values.service.ssh.enabled }}
    - port: {{ .Values.service.ssh.port }}
      targetPort: {{ .Values.service.ssh.portName }}
      protocol: TCP
      name: {{ .Values.service.ssh.portName }}
    {{- end }}
  selector:
    {{- include "gitlab.selectorLabels" . | nindent 4 }}
