apiVersion: v1
kind: Service
metadata:
  name: {{ include "milvus.fullname" . }}-headless
  labels:
    {{- include "milvus.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    {{- range .Values.service.exposedPorts }}
    - port: {{ .portNumber }}
      targetPort: {{ .name }}
      protocol: TCP
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "milvus.selectorLabels" . | nindent 4 }}
