{{- if .Values.resourceQuota.enabled -}}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Values.namespace.name }}-quota
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "kubernetes-namespace.labels" . | nindent 4 }}
spec:
  hard:
    {{- toYaml .Values.resourceQuota.hard | nindent 4 }}
{{- end }}
