apiVersion: v1
kind: Service
metadata:
  name: {{ include "etcd.fullname" . }}
  labels:
    {{- include "etcd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $key, $port := .Values.service.ports }}
    - port: {{ $port.port }}
      targetPort: {{ $port.name }}
      protocol: TCP
      name: {{ $port.name }}
    {{- end }}
    {{- if .Values.metrics.enabled }}
    - port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "etcd.selectorLabels" . | nindent 4 }}
