apiVersion: v2
name: valkey
description: Valkey in-memory key value data store
type: application
version: 0.3.0
appVersion: "8.0"
home: https://github.com/kymeliodev/kymelio-helm
sources:
  - https://github.com/kymeliodev/kymelio-helm
  - https://valkey.io
keywords:
  - valkey
  - redis
  - cache
  - key-value
  - database
maintainers:
  - name: Kymelio
    email: simon.meier@kymelio.com
