apiVersion: v2
name: kubernetes-namespace
description: Provision a Kubernetes namespace with quota, limits and isolation
type: application
version: 0.1.0
appVersion: "1.0.0"
home: https://github.com/kymeliodev/kymelio-helm
sources:
  - https://github.com/kymeliodev/kymelio-helm
keywords:
  - namespace
  - resourcequota
  - limitrange
  - networkpolicy
  - governance
maintainers:
  - name: Kymelio
    email: simon.meier@kymelio.com
