apiVersion: v2
name: opentalk
description: OpenTalk controller for self hosted video conferencing and meetings
type: application
version: 0.4.0
appVersion: "1.0.0"
home: https://github.com/kymeliodev/kymelio-helm
sources:
  - https://github.com/kymeliodev/kymelio-helm
keywords:
  - opentalk
  - video
  - conferencing
  - meetings
  - webrtc
maintainers:
  - name: Kymelio
    email: simon.meier@kymelio.com
