{{- if and .Values.admin.create (not .Values.admin.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "forgejo.fullname" . }}
  labels:
    {{- include "forgejo.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.admin.secretKeys.passwordKey }}: {{ include "forgejo.password" . | b64enc | quote }}
{{- end }}
