{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "plausible.fullname" . }}
  labels:
    {{- include "plausible.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.auth.secretKeys.secretKeyBaseKey }}: {{ include "plausible.secretKeyBase" . | b64enc | quote }}
{{- end }}
