apiVersion: v2
name: odoo
description: Odoo open source ERP and CRM business management suite
type: application
version: 0.1.0
appVersion: "17.0"
home: https://github.com/kymeliodev/kymelio-helm
sources:
  - https://github.com/kymeliodev/kymelio-helm
keywords:
  - odoo
  - erp
  - crm
  - business
  - accounting
maintainers:
  - name: Kymelio
    email: simon.meier@kymelio.com
