apiVersion: v2
name: scylladb
description: ScyllaDB high performance NoSQL database
type: application
version: 0.2.0
appVersion: "6.1"
home: https://github.com/kymeliodev/kymelio-helm
sources:
  - https://github.com/kymeliodev/kymelio-helm
keywords:
  - scylladb
  - database
  - nosql
  - wide-column
  - cassandra
maintainers:
  - name: Kymelio
    email: simon.meier@kymelio.com
