apiVersion: v2
name: authelia
description: Authentication and authorization server providing SSO and 2FA
type: application
version: 0.2.0
appVersion: "4.38"
home: https://github.com/kymeliodev/kymelio-helm
sources:
  - https://github.com/kymeliodev/kymelio-helm
  - https://www.authelia.com
keywords:
  - authelia
  - authentication
  - sso
  - 2fa
  - security
maintainers:
  - name: Kymelio
    email: simon.meier@kymelio.com
