apiVersion: v2
name: cluster-api-operator
description: Cluster API Operator that manages Cluster API providers lifecycle
type: application
version: 0.2.0
appVersion: "v0.12.0"
home: https://github.com/kymeliodev/kymelio-helm
sources:
  - https://github.com/kymeliodev/kymelio-helm
  - https://github.com/kubernetes-sigs/cluster-api-operator
keywords:
  - cluster-api
  - operator
  - providers
  - lifecycle
  - sigs
  - kubernetes
maintainers:
  - name: Kymelio
    email: simon.meier@kymelio.com
