apiVersion: v2
name: velero
description: Velero server for Kubernetes cluster backup, restore and disaster recovery.
type: application
version: 0.4.0
appVersion: "v1.14.0"
home: https://github.com/kymeliodev/kymelio-helm
sources:
  - https://github.com/kymeliodev/kymelio-helm
keywords:
  - velero
  - backup
  - restore
  - disaster-recovery
  - migration
maintainers:
  - name: Kymelio
    email: simon.meier@kymelio.com
