{{- if not .Values.externalDatabase.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "odoo.fullname" . }}
  labels:
    {{- include "odoo.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.externalDatabase.secretKeys.passwordKey }}: {{ include "odoo.password" . | b64enc | quote }}
{{- end }}
