{{- if and .Values.configuration (not .Values.existingConfigMap) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "velero.fullname" . }}-config
  labels:
    {{- include "velero.labels" . | nindent 4 }}
data:
  {{ .Values.configFileName }}: |
    {{- .Values.configuration | nindent 4 }}
{{- end }}
