{{- if .Values.route.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "victoriametrics.fullname" . }}
  labels:
    {{- include "victoriametrics.labels" . | nindent 4 }}
  {{- with .Values.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.route.host }}
  host: {{ . }}
  {{- end }}
  to:
    kind: Service
    name: {{ include "victoriametrics.fullname" . }}
    weight: 100
  {{- with .Values.route.port }}
  port:
    targetPort: {{ . }}
  {{- end }}
  {{- with .Values.route.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  wildcardPolicy: {{ .Values.route.wildcardPolicy }}
{{- end }}
