apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mimir.fullname" . }}
  labels:
    {{- include "mimir.labels" . | nindent 4 }}
data:
  mimir.yaml: |
    {{- .Values.config | nindent 4 }}
