apiVersion: v2
name: opa-gatekeeper
description: Open Policy Agent Gatekeeper admission controller
type: application
version: 0.1.0
appVersion: "v3.17.0"
home: https://github.com/kymeliodev/kymelio-helm
sources:
  - https://github.com/kymeliodev/kymelio-helm
keywords:
  - opa
  - gatekeeper
  - policy
  - admission-control
  - security
maintainers:
  - name: Kymelio
    email: simon.meier@kymelio.com
