apiVersion: v2
name: mosquitto
description: Eclipse Mosquitto MQTT broker deployed as a StatefulSet with persistent storage
type: application
version: 0.1.0
appVersion: "2.0"
home: https://github.com/kymeliodev/kymelio-helm
sources:
  - https://github.com/kymeliodev/kymelio-helm
keywords:
  - mosquitto
maintainers:
  - name: Kymelio
    email: simon.meier@kymelio.com
