apiVersion: v2
name: vault
description: HashiCorp Vault secrets management and data protection server
type: application
version: 0.3.0
appVersion: "1.17.2"
home: https://github.com/kymeliodev/kymelio-helm
sources:
  - https://github.com/kymeliodev/kymelio-helm
  - https://www.vaultproject.io
keywords:
  - vault
  - secrets
  - encryption
  - security
  - pki
maintainers:
  - name: Kymelio
    email: simon.meier@kymelio.com
