apiVersion: v1
kind: Service
metadata:
  name: {{ include "elasticsearch.fullname" . }}
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: {{ .Values.service.http.portName }}
      protocol: TCP
      name: {{ .Values.service.http.portName }}
    - port: {{ .Values.service.transport.port }}
      targetPort: {{ .Values.service.transport.portName }}
      protocol: TCP
      name: {{ .Values.service.transport.portName }}
    {{- if .Values.metrics.enabled }}
    - port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "elasticsearch.selectorLabels" . | nindent 4 }}
