apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.portName }}
      protocol: TCP
      name: {{ .Values.service.portName }}
    {{- if .Values.tls.enabled }}
    - port: {{ .Values.tls.port }}
      targetPort: https
      protocol: TCP
      name: https
    {{- end }}
    {{- if .Values.metrics.enabled }}
    - port: {{ .Values.metrics.port }}
      targetPort: management
      protocol: TCP
      name: management
    {{- end }}
  selector:
    {{- include "keycloak.selectorLabels" . | nindent 4 }}
