apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "authentik.fullname" . }}
  labels:
    {{- include "authentik.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "authentik.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "authentik.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "authentik.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - server
          env:
            - name: AUTHENTIK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "authentik.secretName" . }}
                  key: {{ .Values.auth.secretKeys.secretKeyKey }}
            - name: AUTHENTIK_POSTGRESQL__HOST
              value: {{ .Values.externalDatabase.host | quote }}
            - name: AUTHENTIK_POSTGRESQL__PORT
              value: {{ .Values.externalDatabase.port | quote }}
            - name: AUTHENTIK_POSTGRESQL__NAME
              value: {{ .Values.externalDatabase.database | quote }}
            - name: AUTHENTIK_POSTGRESQL__USER
              value: {{ .Values.externalDatabase.user | quote }}
            - name: AUTHENTIK_REDIS__HOST
              value: {{ .Values.externalRedis.host | quote }}
            - name: AUTHENTIK_REDIS__PORT
              value: {{ .Values.externalRedis.port | quote }}
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: {{ .Values.service.portName }}
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /-/health/live/
              port: {{ .Values.service.portName }}
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /-/health/live/
              port: {{ .Values.service.portName }}
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 6
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
