{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "authentik.fullname" . }}
  labels:
    {{- include "authentik.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.auth.secretKeys.secretKeyKey }}: {{ include "authentik.secretKey" . | b64enc | quote }}
{{- end }}
