apiVersion: v1
kind: Service
metadata:
  name: {{ include "nats.fullname" . }}
  labels:
    {{- include "nats.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.client.port }}
      targetPort: {{ .Values.service.client.portName }}
      protocol: TCP
      name: {{ .Values.service.client.portName }}
    - port: {{ .Values.service.http.port }}
      targetPort: {{ .Values.service.http.portName }}
      protocol: TCP
      name: {{ .Values.service.http.portName }}
    {{- if .Values.metrics.enabled }}
    - port: {{ .Values.service.metrics.port }}
      targetPort: {{ .Values.service.metrics.portName }}
      protocol: TCP
      name: {{ .Values.service.metrics.portName }}
    {{- end }}
  selector:
    {{- include "nats.selectorLabels" . | nindent 4 }}
