apiVersion: v1
kind: Service
metadata:
  name: {{ include "nats.fullname" . }}-headless
  labels:
    {{- include "nats.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.client.port }}
      targetPort: {{ .Values.service.client.portName }}
      protocol: TCP
      name: {{ .Values.service.client.portName }}
    - port: {{ .Values.service.http.port }}
      targetPort: {{ .Values.service.http.portName }}
      protocol: TCP
      name: {{ .Values.service.http.portName }}
  selector:
    {{- include "nats.selectorLabels" . | nindent 4 }}
