apiVersion: v2
name: vector
description: High performance observability data pipeline for logs and metrics
type: application
version: 0.3.0
appVersion: "0.40.0-debian"
home: https://github.com/kymeliodev/kymelio-helm
sources:
  - https://github.com/kymeliodev/kymelio-helm
  - https://vector.dev
keywords:
  - vector
  - logs
  - observability
  - pipeline
  - telemetry
maintainers:
  - name: Kymelio
    email: simon.meier@kymelio.com
