apiVersion: v1
kind: Service
metadata:
  name: {{ include "cockroachdb.fullname" . }}
  labels:
    {{- include "cockroachdb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $key, $p := .Values.service.ports }}
    - port: {{ $p.port }}
      targetPort: {{ $p.name }}
      protocol: TCP
      name: {{ $p.name }}
    {{- end }}
    {{- if .Values.metrics.enabled }}
    - port: {{ .Values.metrics.port }}
      targetPort: {{ .Values.service.ports.http.name }}
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "cockroachdb.selectorLabels" . | nindent 4 }}
