{{- if .Values.metrics.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "cockroachdb.fullname" . }}
  labels:
    {{- include "cockroachdb.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "cockroachdb.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: {{ if .Values.metrics.enabled }}metrics{{ else }}{{ .Values.service.ports.http.name }}{{ end }}
      path: {{ .Values.metrics.path }}
      {{- if .Values.tls.enabled }}
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
      {{- end }}
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
{{- end }}
