{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "couchbase.fullname" . }}
  labels:
    {{- include "couchbase.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.auth.secretKeys.passwordKey }}: {{ include "couchbase.password" . | b64enc | quote }}
  {{- if .Values.metrics.enabled }}
  username: {{ .Values.auth.username | b64enc | quote }}
  {{- end }}
{{- end }}
