apiVersion: v1
kind: Service
metadata:
  name: {{ include "couchbase.fullname" . }}
  labels:
    {{- include "couchbase.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $key, $p := .Values.service.ports }}
    - port: {{ $p.port }}
      targetPort: {{ $p.name }}
      protocol: TCP
      name: {{ $p.name }}
    {{- end }}
    {{- if .Values.tls.enabled }}
    - port: {{ .Values.tls.adminSecurePort }}
      targetPort: admin-tls
      protocol: TCP
      name: admin-tls
    - port: {{ .Values.tls.dataSecurePort }}
      targetPort: data-tls
      protocol: TCP
      name: data-tls
    {{- end }}
  selector:
    {{- include "couchbase.selectorLabels" . | nindent 4 }}
