{{- if .Values.metrics.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "couchbase.fullname" . }}
  labels:
    {{- include "couchbase.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "couchbase.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: {{ .Values.service.ports.admin.name }}
      {{- if .Values.metrics.enabled }}
      path: {{ .Values.metrics.path }}
      basicAuth:
        username:
          name: {{ include "couchbase.secretName" . }}
          key: username
        password:
          name: {{ include "couchbase.secretName" . }}
          key: {{ .Values.auth.secretKeys.passwordKey }}
      {{- end }}
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
{{- end }}
