apiVersion: v2
name: prometheus
description: Prometheus monitoring system and time series database for metrics
type: application
version: 0.3.0
appVersion: "v2.53.1"
home: https://github.com/kymeliodev/kymelio-helm
sources:
  - https://github.com/kymeliodev/kymelio-helm
  - https://prometheus.io
keywords:
  - prometheus
  - monitoring
  - metrics
  - tsdb
  - alerting
maintainers:
  - name: Kymelio
    email: simon.meier@kymelio.com
