{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dragonfly.fullname" . }}
  labels:
    {{- include "dragonfly.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.auth.secretKeys.passwordKey }}: {{ include "dragonfly.password" . | b64enc | quote }}
{{- end }}
