apiVersion: v2
name: weaviate
description: Weaviate vector database with semantic search
type: application
version: 0.3.0
appVersion: "1.26.1"
home: https://github.com/kymeliodev/kymelio-helm
sources:
  - https://github.com/kymeliodev/kymelio-helm
keywords:
  - weaviate
  - vector-database
  - semantic-search
  - embeddings
  - ai
maintainers:
  - name: Kymelio
    email: simon.meier@kymelio.com
