apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "vikunja.fullname" . }}
  labels:
    {{- include "vikunja.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "vikunja.fullname" . }}-headless
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "vikunja.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "vikunja.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "vikunja.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Values.service.portName }}
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: VIKUNJA_SERVICE_PUBLICURL
              value: {{ .Values.vikunja.publicUrl | quote }}
            - name: VIKUNJA_SERVICE_JWTSECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "vikunja.secretName" . }}
                  key: {{ .Values.auth.secretKeys.jwtSecretKey }}
            - name: VIKUNJA_DATABASE_TYPE
              value: {{ .Values.database.type | quote }}
            {{- if eq .Values.database.type "sqlite" }}
            - name: VIKUNJA_DATABASE_PATH
              value: {{ .Values.persistence.mountPath }}/vikunja.db
            {{- else }}
            - name: VIKUNJA_DATABASE_HOST
              value: {{ .Values.externalDatabase.host | quote }}
            - name: VIKUNJA_DATABASE_DATABASE
              value: {{ .Values.externalDatabase.database | quote }}
            - name: VIKUNJA_DATABASE_USER
              value: {{ .Values.externalDatabase.user | quote }}
            - name: VIKUNJA_DATABASE_PASSWORD
              value: {{ .Values.externalDatabase.password | quote }}
            {{- end }}
            - name: VIKUNJA_FILES_BASEPATH
              value: {{ .Values.persistence.mountPath }}
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /api/v1/info
              port: {{ .Values.service.portName }}
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /api/v1/info
              port: {{ .Values.service.portName }}
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if not .Values.persistence.enabled }}
      volumes:
        - name: data
          emptyDir: {}
      {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          {{- toYaml .Values.persistence.accessModes | nindent 10 }}
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
  {{- end }}
