{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "authelia.fullname" . }}
  labels:
    {{- include "authelia.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.auth.secretKeys.jwtKey }}: {{ include "authelia.secretValue" (dict "ctx" . "value" .Values.auth.jwtSecret "key" .Values.auth.secretKeys.jwtKey "length" 64) | b64enc | quote }}
  {{ .Values.auth.secretKeys.sessionKey }}: {{ include "authelia.secretValue" (dict "ctx" . "value" .Values.auth.sessionSecret "key" .Values.auth.secretKeys.sessionKey "length" 64) | b64enc | quote }}
  {{ .Values.auth.secretKeys.storageKey }}: {{ include "authelia.secretValue" (dict "ctx" . "value" .Values.auth.storageEncryptionKey "key" .Values.auth.secretKeys.storageKey "length" 64) | b64enc | quote }}
{{- end }}
