{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "meilisearch.fullname" . }}
  labels:
    {{- include "meilisearch.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.auth.secretKeys.masterKeyKey }}: {{ include "meilisearch.masterKey" . | b64enc | quote }}
{{- end }}
