apiVersion: v2
name: keycloak
description: Open source identity and access management
type: application
version: 0.3.0
appVersion: "25.0"
home: https://github.com/kymeliodev/kymelio-helm
sources:
  - https://github.com/kymeliodev/kymelio-helm
  - https://www.keycloak.org
keywords:
  - keycloak
  - iam
  - identity
  - oidc
  - saml
  - sso
maintainers:
  - name: Kymelio
    email: simon.meier@kymelio.com
