apiVersion: v2
name: influxdb
description: InfluxDB time series database
type: application
version: 0.2.0
appVersion: "2.7"
home: https://github.com/kymeliodev/kymelio-helm
sources:
  - https://github.com/kymeliodev/kymelio-helm
  - https://www.influxdata.com
keywords:
  - influxdb
  - timeseries
  - database
  - metrics
maintainers:
  - name: Kymelio
    email: simon.meier@kymelio.com
