apiVersion: v2
name: elasticsearch
description: Elasticsearch distributed search and analytics engine
type: application
version: 0.1.0
appVersion: "8.15.0"
home: https://github.com/kymeliodev/kymelio-helm
sources:
  - https://github.com/kymeliodev/kymelio-helm
keywords:
  - elasticsearch
  - search
  - analytics
  - full-text
  - lucene
maintainers:
  - name: Kymelio
    email: simon.meier@kymelio.com
