{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paperless-ngx.fullname" . }}
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.auth.secretKeys.secretKeyKey }}: {{ include "paperless-ngx.secretKey" . | b64enc | quote }}
{{- end }}
