{{- if not .Values.auth.existingSecret }}
{{- $masterKey := include "zitadel.masterKey" . }}
{{- if ne (len $masterKey) 32 }}
{{- fail "auth.masterKey must be exactly 32 characters long" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zitadel.fullname" . }}
  labels:
    {{- include "zitadel.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.auth.secretKeys.masterKeyKey }}: {{ $masterKey | b64enc | quote }}
{{- end }}
