{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qdrant.fullname" . }}
  labels:
    {{- include "qdrant.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.auth.secretKeys.apiKeyKey }}: {{ include "qdrant.apiKey" . | b64enc | quote }}
{{- end }}
