apiVersion: v1
kind: Service
metadata:
  name: {{ include "quickwit.fullname" . }}-headless
  labels:
    {{- include "quickwit.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: {{ .Values.service.http.portName }}
      protocol: TCP
      name: {{ .Values.service.http.portName }}
    - port: {{ .Values.service.grpc.port }}
      targetPort: {{ .Values.service.grpc.portName }}
      protocol: TCP
      name: {{ .Values.service.grpc.portName }}
  selector:
    {{- include "quickwit.selectorLabels" . | nindent 4 }}
