apiVersion: v2
name: couchbase
description: Couchbase distributed NoSQL document database
type: application
version: 0.2.0
appVersion: "7.6.2"
home: https://github.com/kymeliodev/kymelio-helm
sources:
  - https://github.com/kymeliodev/kymelio-helm
keywords:
  - couchbase
  - database
  - nosql
  - document
  - key-value
maintainers:
  - name: Kymelio
    email: simon.meier@kymelio.com
