apiVersion: v2
name: thanos
description: Thanos Querier providing a unified query view across Prometheus stores
type: application
version: 0.3.0
appVersion: "v0.36.1"
home: https://github.com/kymeliodev/kymelio-helm
sources:
  - https://github.com/kymeliodev/kymelio-helm
  - https://thanos.io
keywords:
  - thanos
  - querier
  - prometheus
  - metrics
  - monitoring
maintainers:
  - name: Kymelio
    email: simon.meier@kymelio.com
