apiVersion: v2
name: mysql
description: MySQL relational database server
type: application
version: 0.3.0
appVersion: "8.4"
home: https://github.com/kymeliodev/kymelio-helm
sources:
  - https://github.com/kymeliodev/kymelio-helm
  - https://www.mysql.com
keywords:
  - mysql
  - database
  - sql
  - rdbms
maintainers:
  - name: Kymelio
    email: simon.meier@kymelio.com
