apiVersion: v1
kind: Service
metadata:
  name: {{ include "clickhouse.fullname" . }}-headless
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    {{- range $key, $port := .Values.service.ports }}
    - port: {{ $port.port }}
      targetPort: {{ $port.name }}
      protocol: TCP
      name: {{ $port.name }}
    {{- end }}
  selector:
    {{- include "clickhouse.selectorLabels" . | nindent 4 }}
