{{- if .Values.initdbScripts }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgresql.fullname" . }}-initdb
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.initdbScripts | nindent 2 }}
{{- end }}
