{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spicedb.fullname" . }}
  labels:
    {{- include "spicedb.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.auth.secretKeys.presharedKeyKey }}: {{ include "spicedb.presharedKey" . | b64enc | quote }}
{{- end }}
