apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zot.fullname" . }}
  labels:
    {{- include "zot.labels" . | nindent 4 }}
data:
  {{- $config := deepCopy .Values.config }}
  {{- if .Values.metrics.enabled }}
  {{- $extensions := $config.extensions | default dict }}
  {{- $_ := set $extensions "metrics" (dict "enable" true "prometheus" (dict "path" .Values.metrics.path)) }}
  {{- $_ := set $config "extensions" $extensions }}
  {{- end }}
  {{- if .Values.tls.enabled }}
  {{- $http := $config.http | default dict }}
  {{- $_ := set $http "tls" (dict "cert" (printf "%s/%s" .Values.tls.mountPath .Values.tls.certFilename) "key" (printf "%s/%s" .Values.tls.mountPath .Values.tls.keyFilename)) }}
  {{- $_ := set $config "http" $http }}
  {{- end }}
  config.json: |
    {{- toJson $config | nindent 4 }}
