{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mariadb.fullname" . }}
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.auth.secretKeys.rootPasswordKey }}: {{ include "mariadb.rootPassword" . | b64enc | quote }}
  {{ .Values.auth.secretKeys.passwordKey }}: {{ include "mariadb.password" . | b64enc | quote }}
{{- end }}
