apiVersion: v2
name: trivy
description: Trivy vulnerability and misconfiguration scanner in server mode
type: application
version: 0.2.0
appVersion: "0.54.1"
home: https://github.com/kymeliodev/kymelio-helm
sources:
  - https://github.com/kymeliodev/kymelio-helm
keywords:
  - trivy
  - security
  - vulnerability-scanner
  - sbom
  - scanning
maintainers:
  - name: Kymelio
    email: simon.meier@kymelio.com
