{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "rook-ceph.fullname" . }}
  labels:
    {{- include "rook-ceph.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources:
      - pods
      - configmaps
      - services
      - secrets
      - nodes
      - persistentvolumes
      - persistentvolumeclaims
      - events
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources:
      - deployments
      - daemonsets
      - statefulsets
    verbs: ["*"]
  - apiGroups: ["storage.k8s.io"]
    resources:
      - storageclasses
      - csidrivers
      - volumeattachments
    verbs: ["*"]
  - apiGroups: ["ceph.rook.io"]
    resources:
      - "*"
    verbs: ["*"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources:
      - customresourcedefinitions
    verbs: ["*"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources:
      - validatingwebhookconfigurations
      - mutatingwebhookconfigurations
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "rook-ceph.fullname" . }}
  labels:
    {{- include "rook-ceph.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "rook-ceph.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "rook-ceph.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
