apiVersion: v1
kind: Service
metadata:
  name: {{ include "hivemq.fullname" . }}
  labels:
    {{- include "hivemq.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.mqtt.port }}
      targetPort: {{ .Values.service.mqtt.portName }}
      protocol: TCP
      name: {{ .Values.service.mqtt.portName }}
    - port: {{ .Values.service.http.port }}
      targetPort: {{ .Values.service.http.portName }}
      protocol: TCP
      name: {{ .Values.service.http.portName }}
  selector:
    {{- include "hivemq.selectorLabels" . | nindent 4 }}
