apiVersion: v2
name: documenso
description: Documenso open source document signing platform
type: application
version: 0.2.0
appVersion: "1.7.1"
home: https://github.com/kymeliodev/kymelio-helm
sources:
  - https://github.com/kymeliodev/kymelio-helm
keywords:
  - documenso
  - documents
  - signing
  - e-signature
  - collaboration
maintainers:
  - name: Kymelio
    email: simon.meier@kymelio.com
