apiVersion: v2
name: zot
description: OCI native container image registry from Project Zot
type: application
version: 0.1.0
appVersion: "v2.1.1"
home: https://github.com/kymeliodev/kymelio-helm
sources:
  - https://github.com/kymeliodev/kymelio-helm
  - https://zotregistry.dev
keywords:
  - zot
  - registry
  - oci
  - container
  - artifacts
maintainers:
  - name: Kymelio
    email: simon.meier@kymelio.com
