apiVersion: v2
name: surrealdb
description: SurrealDB multi-model database
type: application
version: 0.2.0
appVersion: "v2.0"
home: https://github.com/kymeliodev/kymelio-helm
sources:
  - https://github.com/kymeliodev/kymelio-helm
  - https://surrealdb.com
keywords:
  - surrealdb
  - database
  - nosql
  - multi-model
maintainers:
  - name: Kymelio
    email: simon.meier@kymelio.com
