{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minio.fullname" . }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.auth.secretKeys.rootUserKey }}: {{ .Values.auth.rootUser | b64enc | quote }}
  {{ .Values.auth.secretKeys.rootPasswordKey }}: {{ include "minio.rootPassword" . | b64enc | quote }}
{{- end }}
