apiVersion: v2
name: seaweedfs
description: SeaweedFS distributed object and file storage running master, volume and filer in one server.
type: application
version: 0.1.0
appVersion: "3.71"
home: https://github.com/kymeliodev/kymelio-helm
sources:
  - https://github.com/kymeliodev/kymelio-helm
keywords:
  - seaweedfs
  - storage
  - object-storage
  - filesystem
  - distributed
  - s3
maintainers:
  - name: Kymelio
    email: simon.meier@kymelio.com
