apiVersion: v1
kind: Service
metadata:
  name: {{ include "questdb.fullname" . }}-headless
  labels:
    {{- include "questdb.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    {{- range $name, $port := .Values.service.ports }}
    - port: {{ $port }}
      targetPort: {{ $name }}
      protocol: TCP
      name: {{ $name }}
    {{- end }}
  selector:
    {{- include "questdb.selectorLabels" . | nindent 4 }}
