apiVersion: v2
name: grafana
description: Grafana observability platform for metrics, logs and traces dashboards
type: application
version: 0.2.0
appVersion: "11.1.4"
home: https://github.com/kymeliodev/kymelio-helm
sources:
  - https://github.com/kymeliodev/kymelio-helm
  - https://grafana.com
keywords:
  - grafana
  - dashboards
  - observability
  - visualization
  - monitoring
maintainers:
  - name: Kymelio
    email: simon.meier@kymelio.com
