apiVersion: v2
name: redpanda
description: Redpanda Kafka-compatible streaming data platform deployed as a single node StatefulSet
type: application
version: 0.4.0
appVersion: "v24.2.2"
home: https://github.com/kymeliodev/kymelio-helm
sources:
  - https://github.com/kymeliodev/kymelio-helm
keywords:
  - redpanda
maintainers:
  - name: Kymelio
    email: simon.meier@kymelio.com
