apiVersion: v2
name: cockroachdb
description: CockroachDB distributed SQL database
type: application
version: 0.1.0
appVersion: "v24.2.4"
home: https://github.com/kymeliodev/kymelio-helm
sources:
  - https://github.com/kymeliodev/kymelio-helm
keywords:
  - cockroachdb
  - database
  - sql
  - distributed
  - newsql
maintainers:
  - name: Kymelio
    email: simon.meier@kymelio.com
