{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "neo4j.fullname" . }}
  labels:
    {{- include "neo4j.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.auth.secretKeys.authKey }}: {{ include "neo4j.authString" . | b64enc | quote }}
{{- end }}
