{{- if .Values.podDisruptionBudget.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "sealed-secrets.fullname" . }}
  labels:
    {{- include "sealed-secrets.labels" . | nindent 4 }}
spec:
  {{- with .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ . }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sealed-secrets.selectorLabels" . | nindent 6 }}
{{- end }}
