{{- if .Values.metrics.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "couchdb.fullname" . }}
  labels:
    {{- include "couchdb.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "couchdb.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: {{ if .Values.metrics.enabled }}metrics{{ else }}{{ .Values.service.portName }}{{ end }}
      {{- if .Values.metrics.enabled }}
      path: {{ .Values.metrics.path }}
      {{- end }}
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
{{- end }}
