apiVersion: v1
kind: Service
metadata:
  name: {{ include "kamaji.fullname" . }}
  labels:
    {{- include "kamaji.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.portName }}
      protocol: TCP
      name: {{ .Values.service.portName }}
    - port: {{ .Values.service.webhookPort }}
      targetPort: {{ .Values.service.webhookPortName }}
      protocol: TCP
      name: {{ .Values.service.webhookPortName }}
  selector:
    {{- include "kamaji.selectorLabels" . | nindent 4 }}
