apiVersion: v2
name: milvus
description: Milvus vector database for similarity search and AI applications
type: application
version: 0.1.0
appVersion: "v2.4.6"
home: https://github.com/kymeliodev/kymelio-helm
sources:
  - https://github.com/kymeliodev/kymelio-helm
keywords:
  - milvus
  - vector-database
  - embeddings
  - similarity-search
  - ai
maintainers:
  - name: Kymelio
    email: simon.meier@kymelio.com
