apiVersion: v1
kind: Service
metadata:
  name: {{ include "vernemq.fullname" . }}
  labels:
    {{- include "vernemq.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.mqtt.port }}
      targetPort: {{ .Values.service.mqtt.portName }}
      protocol: TCP
      name: {{ .Values.service.mqtt.portName }}
    - port: {{ .Values.service.epmd.port }}
      targetPort: {{ .Values.service.epmd.portName }}
      protocol: TCP
      name: {{ .Values.service.epmd.portName }}
  selector:
    {{- include "vernemq.selectorLabels" . | nindent 4 }}
