apiVersion: v1
kind: Service
metadata:
  name: {{ include "vernemq.fullname" . }}
  labels:
    {{- include "vernemq.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.mqtt.port }}
      targetPort: {{ .Values.service.mqtt.portName }}
      protocol: TCP
      name: {{ .Values.service.mqtt.portName }}
    {{- if .Values.tls.enabled }}
    - port: {{ .Values.tls.mqttsPort }}
      targetPort: {{ .Values.tls.mqttsPortName }}
      protocol: TCP
      name: {{ .Values.tls.mqttsPortName }}
    {{- end }}
    - port: {{ .Values.service.epmd.port }}
      targetPort: {{ .Values.service.epmd.portName }}
      protocol: TCP
      name: {{ .Values.service.epmd.portName }}
    {{- if .Values.metrics.enabled }}
    - port: {{ .Values.service.metrics.port }}
      targetPort: {{ .Values.service.metrics.portName }}
      protocol: TCP
      name: {{ .Values.service.metrics.portName }}
    {{- end }}
  selector:
    {{- include "vernemq.selectorLabels" . | nindent 4 }}
