{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "superset.fullname" . }}
  labels:
    {{- include "superset.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.auth.secretKeys.secretKey }}: {{ include "superset.secretKey" . | b64enc | quote }}
{{- end }}
