{{- if .Values.metrics.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "nexus.fullname" . }}
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "nexus.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: {{ .Values.service.portName }}
      path: {{ .Values.metrics.path }}
      {{- with .Values.metrics.serviceMonitor.basicAuthSecret }}
      basicAuth:
        username:
          name: {{ . }}
          key: {{ $.Values.metrics.serviceMonitor.usernameKey }}
        password:
          name: {{ . }}
          key: {{ $.Values.metrics.serviceMonitor.passwordKey }}
      {{- end }}
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
{{- end }}
