apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mosquitto.fullname" . }}-config
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
data:
  mosquitto.conf: |-
    listener 1883
    allow_anonymous true
    persistence true
    persistence_location /mosquitto/data/
