apiVersion: v2
name: kyverno
description: Kyverno policy engine for Kubernetes
type: application
version: 0.3.0
appVersion: "v1.12.5"
home: https://github.com/kymeliodev/kymelio-helm
sources:
  - https://github.com/kymeliodev/kymelio-helm
keywords:
  - kyverno
  - policy
  - security
  - governance
  - admission-control
maintainers:
  - name: Kymelio
    email: simon.meier@kymelio.com
