{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "influxdb.fullname" . }}
  labels:
    {{- include "influxdb.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.auth.secretKeys.passwordKey }}: {{ include "influxdb.password" . | b64enc | quote }}
{{- end }}
