{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.auth.secretKeys.passwordKey }}: {{ include "rabbitmq.password" . | b64enc | quote }}
  {{ .Values.auth.secretKeys.erlangCookieKey }}: {{ include "rabbitmq.erlangCookie" . | b64enc | quote }}
{{- end }}
