apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.amqp.port }}
      targetPort: {{ .Values.service.amqp.portName }}
      protocol: TCP
      name: {{ .Values.service.amqp.portName }}
    {{- if .Values.tls.enabled }}
    - port: {{ .Values.tls.amqpsPort }}
      targetPort: {{ .Values.tls.amqpsPortName }}
      protocol: TCP
      name: {{ .Values.tls.amqpsPortName }}
    {{- end }}
    - port: {{ .Values.service.management.port }}
      targetPort: {{ .Values.service.management.portName }}
      protocol: TCP
      name: {{ .Values.service.management.portName }}
    {{- if .Values.metrics.enabled }}
    - port: {{ .Values.service.metrics.port }}
      targetPort: {{ .Values.service.metrics.portName }}
      protocol: TCP
      name: {{ .Values.service.metrics.portName }}
    {{- end }}
  selector:
    {{- include "rabbitmq.selectorLabels" . | nindent 4 }}
