{{- if and .Values.devMode.enabled (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vault.fullname" . }}
  labels:
    {{- include "vault.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.auth.secretKeys.rootTokenKey }}: {{ include "vault.rootToken" . | b64enc | quote }}
{{- end }}
