apiVersion: v1
kind: Service
metadata:
  name: {{ include "airlock-microgateway.fullname" . }}
  labels:
    {{- include "airlock-microgateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.portName }}
      protocol: TCP
      name: {{ .Values.service.portName }}
    {{- if .Values.metrics.enabled }}
    - port: {{ .Values.metrics.port }}
      targetPort: {{ .Values.service.portName }}
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "airlock-microgateway.selectorLabels" . | nindent 4 }}
