{{- if .Values.metrics.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "airlock-microgateway.fullname" . }}
  labels:
    {{- include "airlock-microgateway.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "airlock-microgateway.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: {{ if .Values.metrics.enabled }}metrics{{ else }}{{ .Values.service.portName }}{{ end }}
      path: /metrics
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
{{- end }}
