apiVersion: v2
name: etcd
description: etcd distributed reliable key value store
type: application
version: 0.2.0
appVersion: "v3.5.16"
home: https://github.com/kymeliodev/kymelio-helm
sources:
  - https://github.com/kymeliodev/kymelio-helm
keywords:
  - etcd
  - key-value
  - distributed
  - consensus
  - configuration
maintainers:
  - name: Kymelio
    email: simon.meier@kymelio.com
