{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "outline.fullname" . }}
  labels:
    {{- include "outline.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.auth.secretKeys.secretKey }}: {{ include "outline.generatedSecret" (dict "ctx" . "key" .Values.auth.secretKeys.secretKey "len" 32) | b64enc | quote }}
  {{ .Values.auth.secretKeys.utilsSecretKey }}: {{ include "outline.generatedSecret" (dict "ctx" . "key" .Values.auth.secretKeys.utilsSecretKey "len" 32) | b64enc | quote }}
{{- end }}
