apiVersion: v2
name: clickhouse
description: ClickHouse column oriented OLAP database
type: application
version: 0.4.0
appVersion: "24.8"
home: https://github.com/kymeliodev/kymelio-helm
sources:
  - https://github.com/kymeliodev/kymelio-helm
keywords:
  - clickhouse
  - database
  - olap
  - analytics
  - columnar
maintainers:
  - name: Kymelio
    email: simon.meier@kymelio.com
