apiVersion: v2
name: rabbitmq
description: Multi protocol message broker implementing AMQP
type: application
version: 0.1.1
appVersion: "3.13"
home: https://github.com/kymeliodev/kymelio-helm
sources:
  - https://github.com/kymeliodev/kymelio-helm
  - https://www.rabbitmq.com
keywords:
  - rabbitmq
  - amqp
  - message-broker
  - queue
  - messaging
maintainers:
  - name: Kymelio
    email: simon.meier@kymelio.com
