apiVersion: v1
kind: Service
metadata:
  name: {{ include "activemq.fullname" . }}
  labels:
    {{- include "activemq.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.openwire.port }}
      targetPort: {{ .Values.service.openwire.portName }}
      protocol: TCP
      name: {{ .Values.service.openwire.portName }}
    - port: {{ .Values.service.web.port }}
      targetPort: {{ .Values.service.web.portName }}
      protocol: TCP
      name: {{ .Values.service.web.portName }}
  selector:
    {{- include "activemq.selectorLabels" . | nindent 4 }}
