{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "typesense.fullname" . }}
  labels:
    {{- include "typesense.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.auth.secretKeys.apiKeyKey }}: {{ include "typesense.apiKey" . | b64enc | quote }}
{{- end }}
