apiVersion: v1
kind: Service
metadata:
  name: {{ include "typesense.fullname" . }}-headless
  labels:
    {{- include "typesense.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.portName }}
      protocol: TCP
      name: {{ .Values.service.portName }}
  selector:
    {{- include "typesense.selectorLabels" . | nindent 4 }}
