apiVersion: v1
kind: Service
metadata:
  name: {{ include "pulsar.fullname" . }}
  labels:
    {{- include "pulsar.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.pulsar.port }}
      targetPort: {{ .Values.service.pulsar.portName }}
      protocol: TCP
      name: {{ .Values.service.pulsar.portName }}
    {{- if .Values.tls.enabled }}
    - port: {{ .Values.tls.tlsPort }}
      targetPort: {{ .Values.tls.tlsPortName }}
      protocol: TCP
      name: {{ .Values.tls.tlsPortName }}
    {{- end }}
    - port: {{ .Values.service.http.port }}
      targetPort: {{ .Values.service.http.portName }}
      protocol: TCP
      name: {{ .Values.service.http.portName }}
  selector:
    {{- include "pulsar.selectorLabels" . | nindent 4 }}
