apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "pulsar.fullname" . }}
  labels:
    {{- include "pulsar.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "pulsar.fullname" . }}-headless
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "pulsar.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pulsar.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
{{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pulsar.serviceAccountName" . }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      securityContext:
        {{- if .Values.openShift.enabled }}
        {{- omit .Values.podSecurityContext "runAsUser" "runAsGroup" "fsGroup" | toYaml | nindent 8 }}
        {{- else }}
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
        {{- end }}
      {{- with .Values.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - bin/pulsar
          args:
            - standalone
            {{- with .Values.extraArgs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: {{ .Values.service.pulsar.portName }}
              containerPort: {{ .Values.service.pulsar.port }}
              protocol: TCP
            {{- if .Values.tls.enabled }}
            - name: {{ .Values.tls.tlsPortName }}
              containerPort: {{ .Values.tls.tlsPort }}
              protocol: TCP
            {{- end }}
            - name: {{ .Values.service.http.portName }}
              containerPort: {{ .Values.service.http.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /admin/v2/brokers/health
              port: {{ .Values.service.http.portName }}
            initialDelaySeconds: 45
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /admin/v2/brokers/health
              port: {{ .Values.service.http.portName }}
            initialDelaySeconds: 45
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if or .Values.pulsarConf .Values.tls.enabled .Values.extraEnv }}
          env:
            {{- range $key, $value := .Values.pulsarConf }}
            - name: PULSAR_PREFIX_{{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- if .Values.tls.enabled }}
            - name: PULSAR_PREFIX_tlsEnabled
              value: "true"
            - name: PULSAR_PREFIX_brokerServicePortTls
              value: {{ .Values.tls.tlsPort | quote }}
            - name: PULSAR_PREFIX_tlsCertificateFilePath
              value: {{ printf "%s/%s" .Values.tls.mountPath .Values.tls.certFilename | quote }}
            - name: PULSAR_PREFIX_tlsKeyFilePath
              value: {{ printf "%s/%s" .Values.tls.mountPath .Values.tls.keyFilename | quote }}
            - name: PULSAR_PREFIX_tlsTrustCertsFilePath
              value: {{ printf "%s/%s" .Values.tls.mountPath .Values.tls.caFilename | quote }}
            - name: PULSAR_PREFIX_tlsRequireTrustedClientCertOnConnect
              value: {{ .Values.tls.requireTrustedClientCertOnConnect | quote }}
            {{- end }}
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- with .Values.extraEnvFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
            {{- if or .Values.configuration .Values.existingConfigMap }}
            - name: config
              mountPath: {{ .Values.configMountPath }}
              {{- with .Values.configSubPath }}
              subPath: {{ . }}
              {{- end }}
            {{- end }}
            {{- if .Values.tls.enabled }}
            - name: certs
              mountPath: {{ .Values.tls.mountPath }}
              readOnly: true
            {{- end }}
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        {{- with .Values.sidecars }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or (not .Values.persistence.enabled) .Values.configuration .Values.existingConfigMap .Values.tls.enabled .Values.extraVolumes }}
      volumes:
        {{- if not .Values.persistence.enabled }}
        - name: data
          emptyDir: {}
        {{- end }}
        {{- if or .Values.configuration .Values.existingConfigMap }}
        - name: config
          configMap:
            name: {{ if .Values.existingConfigMap }}{{ .Values.existingConfigMap }}{{ else }}{{ include "pulsar.fullname" . }}-config{{ end }}
        {{- end }}
        {{- if .Values.tls.enabled }}
        - name: certs
          secret:
            secretName: {{ .Values.tls.existingSecret }}
        {{- end }}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          {{- toYaml .Values.persistence.accessModes | nindent 10 }}
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
  {{- end }}
